post/api/urls.py
from django.urls import path
from .views import (
        PostAPIView, 
        PostDetailAPIView,
        CommentCreateApiView,
        CommentListAPIView,
        CommentDetialAPIView
        )


app_name = 'post_api'

urlpatterns = [
    path('posts/', PostAPIView.as_view(), name='posts'),
    path('posts/<slug:slug>/', PostDetailAPIView.as_view(), name='post'),
    path('posts/<slug:slug>/comment/', CommentCreateApiView.as_view(), name='create_comment'),
    path('comments/', CommentListAPIView.as_view(), name='comments'),
    path('comments/<int:pk>/', CommentDetialAPIView.as_view(), name='comment'),

]

post/urls.py
from django.urls import path
from .views import PostList, PostDetail, CommentDelete

app_name = 'post'

urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('comment/delete/<int:pk>', CommentDelete.as_view(), name='delete_comment'),
    path('<slug:slug>/', PostDetail.as_view(), name='post'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import  i18n_patterns
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(
   openapi.Info(
      title="Blog API",
      default_version='v1',
      description="API for this blog",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('api/', include('account.api.urls')),
    path('api/', include('post.api.urls', namespace='post_api')),

    path('api/docs/', include_docs_urls(title='Blog APi')),
    path('api/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('post.urls', namespace='post')),
    # prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
import os
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.template.defaultfilters import slugify
from django.utils.translation import get_language
from PIL import Image
from unidecode import unidecode

def upload_image(instance, image_name):
    """ Make a path to the post image and change the name of the image to a post id

    Returns:
        [str]: [image path]
    """
    _ , extension = os.path.splitext(image_name)

    # return f"post_images/{instance.id}.{extension}"   
    return f"post_images/{instance.title}.{extension}"   

active_field_choices = [
    (True, _('Active')),
    (False, _('Inactive'))
]

class Language(models.Model):
    name = models.CharField(_('name'), max_length=25, null=True, blank=True)
    code = models.CharField(_('code'), max_length=5, null=True, blank=True)
    created_at = models.DateTimeField(_('created at'), auto_now=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now_add=True)
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)

    def __str__(self):
        return self.code
    
class Category(models.Model):
    name = models.CharField(_('name'), max_length=50)
    
    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        
    def __str__(self):
        return self.name
     
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('author'))
    title = models.CharField(_('title'), max_length=100)
    content = models.TextField(_('content'), max_length=4000)
    categories = models.ManyToManyField(Category, blank=True, verbose_name=_('categories'))
    image = models.ImageField(_('image'), upload_to=upload_image, blank=True, null=True)
    created_at = models.DateTimeField(_('created at'), auto_now=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now_add=True)
    published_at = models.DateTimeField(_('published at'), default=now)
    views_count = models.IntegerField(_('views count'), null=True, blank=True, default=0, editable=False)
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='posts', verbose_name=_('language'), null=True, blank=True)
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)
    slug = models.SlugField(null=True, blank=True, unique=True, max_length=100, allow_unicode=True)
    
    class Meta:
        ordering = ('-published_at', )
    
    @property
    def get_self_or_post_lang(self):
        # check are language existin Language model
        try:
            lang = Language.objects.get(code=get_language())
        except Language.DoesNotExist: # if not retrun default title
            return self
                    
        if self.language == lang:
            return self
        
        post_lang = self.post_lang.filter(language = lang)
        
        if post_lang:
            return post_lang.get()
        
        return self
        
    def get_title(self):
        return self.get_self_or_post_lang.title
    
    def get_content(self):
        return self.get_self_or_post_lang.content
    
    def get_categories(self):
        return self.get_self_or_post_lang.categories
    
    def get_language_code(self):
        return self.get_self_or_post_lang.language.code
            
        
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        """
            Overwrite save mehtod to make a slug to post, rename a image and resize a big image
        """

        # Make a post Slug
        if not self.pk:
            slug = slugify(unidecode(f"{self.title}"))

            slug_count = len(Post.objects.filter(slug=slug))
            if slug_count > 0:
                slug = f"{slug}-{slug_count}"

            self.slug = slug
            

        # Handle problem in upload_image function  (pk not generator yet)
        # if self.pk is None:
        #     post_image = self.image
        #     self.image = None
        #     super().save(*args, **kwargs)
        #     self.image = post_image

        super().save(*args, **kwargs)
        
        # image resize
        if self.image:
            try:
                img = Image.open(self.image.path)   
                if img.width > 800 or img.height > 800:
                    img.thumbnail( (800, 800) )
                    img.save(self.image.path)
            except:
                pass

class PostLanguage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_lang', verbose_name=_('post'))
    title = models.CharField(_('title'), max_length=100)
    content = models.TextField(_('content'), max_length=4000)
    categories = models.ManyToManyField(Category, blank=True, verbose_name=_('categories'))
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='posts_lan', verbose_name=_('language'))
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name=_('user'))
    content = models.TextField(_('content'), max_length=300)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, related_name='comments', verbose_name=_('post'),)
    created_at = models.DateTimeField(_('created at'), auto_now=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now_add=True)
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)
    
    def __str__(self):
        return self.content

post/forms.py
from django import  forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
        

post/api/views.py
from django.utils.timezone import now
from django.db.models import Q
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
    CreateAPIView,
    ListAPIView
    )
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from post.models import Post, Comment
from .serializers import (
    PostSerializer,
    PostDetailSerializer,
    PostCommentSerailzer,
    CommentSerailzer
    )
from .permissions import IsAuthorOrReadOnly, IsOwnerOrReadOnly

class PostAPIView(ListCreateAPIView):
    queryset = Post.objects.filter( Q(active=True) & Q(published_at__lte=now()) )
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class PostDetailAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.filter( Q(active=True) & Q(published_at__lte=now()) )
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]
    lookup_field = 'slug'


class CommentCreateApiView(CreateAPIView):
    model = Comment
    serializer_class = PostCommentSerailzer
    permission_classes = [IsAuthenticated,]


    def perform_create(self, serializer):
        slug = self.kwargs['slug']
        post = Post.objects.get(slug=slug)

        serializer.save(user=self.request.user, post=post)


class CommentListAPIView(ListAPIView):
    queryset = Comment.objects.filter(active=True)
    serializer_class = CommentSerailzer
    

class CommentDetialAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.filter(active=True)
    serializer_class = CommentSerailzer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

post/views.py
import random
from django.shortcuts import reverse
from django.views.generic import ListView, DetailView, DeleteView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.utils.timezone import now
from django.db.models import Q
from post.models import Post, Comment
from post.forms import CommentForm

class PostList(ListView):
    """ Home page """
    model = Post
    template_name = 'post/posts.html'
    context_object_name = 'posts'
    paginate_by = 10
    def get_queryset(self):
        # render posts that active = true and published_at before now
        queryset = self.model.objects.filter( Q(active=True) & Q(published_at__lte=now()) )
        
        # filter posts by categories => if url path has a ?category=
        category = self.request.GET.get('category')
        
        
        if category:
            queryset = queryset.filter(categories__name=category)
            
        # Search Field
        qs = self.request.GET.get('q')
        
        if qs:
            qs = qs.strip()
            queryset = queryset.filter( Q(title__icontains=qs) | Q(content__icontains=qs) )
            
        return queryset
    
    
class PostDetail(FormMixin, DetailView):
    model = Post
    template_name = 'post/post.html'
    context_object_name = 'post'
    form_class = CommentForm
    
    def get(self, request, *args, **kwargs):
        """ 
        overwrite get function to incrase views_count by 1 

        """
        post = self.get_object()
        post.views_count += 1
        post.save()
        return super().get(request,*args, **kwargs)
    
            
    def get_queryset(self):
        # render posts that active = true and published_at before now
        return self.model.objects.filter( Q(active=True) & Q(published_at__lte=now()) )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        # related posts 

        posts = self.get_queryset()
        obj_categories = post.categories.all() # get object categories

        related_posts = None
        if obj_categories: # Are object has category
            related_posts = posts.filter(categories__in=obj_categories)[:3]

        # if related_posts none render 3 random posts
        if not related_posts:
            posts_list = list(posts)
            related_posts = random.sample(posts_list, min(len(posts_list), 3))

        context['related_posts'] = related_posts

        # comments
        comments = Comment.objects.filter( Q(post=post) & Q(active=True) )

        context['comments'] = comments

        context['comment_form'] = CommentForm

        return context
    
    
    def post(self, request, *args, **kwargs):
        self.obj = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)
        
    def form_valid(self, form):
        form_2 = form.save(commit=False)
        form_2.user = self.request.user
        form_2.post = self.get_object()
        form_2.save()
        return super().form_valid(form)        
    
    def get_success_url(self):
        return reverse('post:post',  kwargs={'slug': self.get_object().slug})


class CommentDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    
    def test_func(self):
        user = self.request.user
        return self.get_object().user == user or user.is_superuser or user.profile.is_admin
    
    def get_success_url(self):
        return reverse('post:post', kwargs={'slug':self.object.post.slug})
    

post/templates/post/comment_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<p>{% translate 'are you sure you want to delete comment' %} "{{object}}" ?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input class="danger" type="submit" value="{% trans 'yes delete' %}">
    <a class="btn" href="{% url 'post:post' object.post.slug %}">{% trans 'No' %}</a>
</form>
{% endblock content %}

post/templates/post/most_view_posts.html
{% load i18n %}
{% load static %}
<h3>{% trans 'most view posts' %}</h3>
{% for post in m_posts %}
<a href="{% url 'post:post' post.slug %}">
	<article>
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="Image Post">
        {% else %}
            <img src="{% static 'image/default.jpg' %}" alt="Image Post">
        {% endif %}
		<div class="article-content">
		<h2>{{post.get_title}}</h2>
      <ul>
      <li class="date">
          <i class="far fa-calendar"></i>
          {{post.published_at|date:"M d, Y"}}
      </li>
      </ul>
		</div>
	</article> 
</a>                                   
{% endfor %}

post/templates/post/pagination.html
{% load i18n %}
<div class="pagination">
	<p>{% trans 'page' %} {{page_obj.number}} {% trans 'of' %} {{page_obj.paginator.num_pages}}</p>
	<div class="icon">
			{% if page_obj.has_previous %}
					<a href="?q={{request.GET.q}}&category={{request.GET.category}}&page={{page_obj.previous_page_number}}"><i class="fas fa-angle-double-left"></i></a>
			{% endif %}
	</div>
	<ul>
	{% for page in page_obj.paginator.page_range %}
			{% if page == page_obj.number or page == page_obj.number|add:'1' %}
				<li
						{% if page == page_obj.number %}
								class="active"
						{% endif %}
				>
				<a href="?q={{request.GET.q}}&category={{request.GET.category}}&page={{page}}">{{page}}</a>
				</li>
			{% elif page == page_obj.number|add:'-1' %}
					<li><a href="?q={{request.GET.q}}&category={{request.GET.category}}&page={{page}}">{{page}}</a></li>
			{% elif page == page_obj.number|add:'2' %}
					<li><a href="?q={{request.GET.q}}&category={{request.GET.category}}&page={{page}}">{{page}}</a></li>
					<li class="points" >...</li>
					<li><a href="?q={{request.GET.q}}&category={{request.GET.category}}&page={{page}}">{{page_obj.paginator.num_pages}}</a></li>
			{% endif %}
	{% endfor %}
	</ul>
		<div class="icon">
			{% if page_obj.has_next %}
					<a href="?q={{request.GET.q}}&category={{request.GET.category}}&page={{page_obj.next_page_number}}"><i class="fas fa-angle-double-left"></i></a>
			{% endif %}
		</div>
</div>

post/templates/post/post.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{{post.get_title}}{% endblock title %}
{% block content %}
<div class="post">
<article>
	        {% get_current_language as LANGUAGE_CODE %}
        {% if post.get_language_code != LANGUAGE_CODE %}
          <p class="no-translate">{% translate 'There is no translation for this article' %}</p>
        {% endif %}
  <div class="post-header">
		<div class="header">
			<h1>{{post.get_title}}</h1>
			<p>{% blocktranslate with views=post.views_count %}{{views}} views {% endblocktranslate %}</p>
		</div>
		<ul>
			<li class="category">
				{% for category in post.get_categories.all %}  
					<a href="{% url 'post:home' %}?category={{category}}">{{category}}</a>
				{% endfor %}
			</li>
			<li class="date">
					<i class="far fa-calendar"></i>
					{{post.published_at|date:"M d, Y"}}
			</li>
			<li class="user-icon">
			  <i class="far fa-user"></i>
			  {{post.author}}
			</li>		
		</ul>
	</div>
          {% if post.image %}
            	<img src="{{ post.image.url }}" alt="Image Post">
          {% endif %}
	<p>
		{{post.get_content}}
	</p>
</article>
<div class="related-posts">
	<h2>{% trans 'related posts' %}</h2>
	<div class="posts">
		{% for related_post in related_posts %}
			<article>
				<a href="{% url 'post:home' %}">
					{% if related_post.image %}
            			<img src="{{ related_post.image.url }}" alt="Image Post">
          			{% else %}
            			<img src="{% static 'image/default.jpg' %}" alt="Image Post">
          			{% endif %}
					<h3>{{related_post.get_title}}</h3>
				</a>
			</article>
		{% empty %}
			{% trans 'no related posts' %}
		{% endfor %}
	</div>
</div>
<div class="comment">
	<h3 class="comments-header" >{% trans 'comments' %}</h3>
	{% for comment in comments %}
		<div class="comment-content">
			<div class="image">
				<img src="http://127.0.0.1:8000/media/post_images/default.jpg" alt="">
			</div>
			<div class="box">
				<div class="header">
					<h6><a href="">{{comment.user.username}}</a></h6>
					<span>{{comment.created_at}}</span>
				</div>
				<div class="cont">
					<p>{{comment.content}}</p>
					{% if comment.user == user %}
						<div class="icons">
							<a href="{% url 'post:delete_comment' comment.id %}" alt="{% trans 'delete' %}"><i class="far fa-trash-alt"></i></a>
							<!-- <a href="#" alt="Edit"><i class="far fa-edit"></i></a> -->
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	{% endfor %}
	{% if request.user.is_authenticated %}
		<form action="" method="POST">
			<h3 class="comments-header" >{% trans 'write comment' %}</h3>
			{% csrf_token %}
			{{comment_form}}
			<input type="submit" value="{% trans 'post comment' %}">
		</form>
		{% else %}
		{% url 'login' as login %}
		<p>{% blocktranslate %}you are not logged in, please<a href="{{login}}">login</a> and leave a comment.{% endblocktranslate %}</p>
	{% endif %}		
</div>
</div>
{% endblock content %}

post/templates/post/posts.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="articles">
  {% for post in posts %}
  <article>
    <div class="image">
        <a href="{% url 'post:post' post.slug %}">
          {% if post.image %}
            <img src="{{ post.image.url }}" alt="Image Post">
          {% else %}
            <img src="{% static 'image/default.jpg' %}" alt="Image Post">
          {% endif %}
        </a>
      </div>
      <div class="article-content">
        <h2><a href="{% url 'post:post' post.slug %}">
          {{post.get_title}}
        </a></h2>
        {% get_current_language as LANGUAGE_CODE %}
        {% if post.get_language_code != LANGUAGE_CODE %}
          <p class="no-translate">{% translate 'There is no translation for this article' %}</p>
        {% endif %}
        <ul>
      <li class="category">
        {% for category in post.get_categories.all %}  
          <a href="?category={{category}}">{{category}}</a>
        {% endfor %}
      </li>
      <li class="date">
          <i class="far fa-calendar"></i>
          {{post.published_at|date:"M d, Y"}}
      </li>
      </ul>
      <p>
        {{post.get_content|truncatewords:"30"}}
      </p>
    </div>
  </article>
  {% empty %}
  <h2>No Posts Yet</h2>
  {% endfor %}
</div>
{% include 'post/pagination.html' %}
{% endblock content %}