account/urls.py
from django.urls import path, include
from .views import LoginPage, RegisterView, LogoutPage, ProfileView
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    
    path('profile/', ProfileView.as_view(), name='profile'),
    
    path('password_change/', PasswordChangeView.as_view(template_name='account/password_change.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name='password_change_done'),
    
    path('password_reset/', PasswordResetView.as_view(template_name='account/password_reset.html'), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),

]

dashboard/urls.py
from django.urls import path
from  .views import (
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostLanguageListView,
    PostLanguageCreateView,
    PostLanguageUpdateView,
    PostLanguageDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    CommentListView,
    AccountListView,
    AccountCreateView,
    AccountUpdateView,
    AccountDeleteView,
    LanguageListView,
    LanguageCreateView,
    LanguageUpdateView,
    LanguageDeleteView,
    )

app_name = 'dashboard'

urlpatterns = [
    # Post Urls
    path('dashboard/', PostListView.as_view(), name='dashboard'),
    
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    
    path('posts/translation/', PostLanguageListView.as_view(), name='posts_language'),
    path('post/add/translation/<int:id>/', PostLanguageCreateView.as_view(), name='post_language_create'),
    path('post/update/translation/<int:pk>/', PostLanguageUpdateView.as_view(), name='post_language_update'),
    path('post/delete/translation/<int:pk>/', PostLanguageDeleteView.as_view(), name='post_language_delete'),
    
    # Categories Urls
    path('category/', CategoryListView.as_view(), name='categories'),
    path('category/create/', CategoryCreateView.as_view(), name='create_category'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='update_category'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='delete_category'),
    
    # Comments Urls
    path('comment/', CommentListView.as_view(), name='comments'),
    
    # Accounts Urls
    path('account/', AccountListView.as_view(), name='accounts'),
    path('account/create/', AccountCreateView.as_view(), name='accounts_create'),
    path('account/update/<int:pk>/', AccountUpdateView.as_view(), name='accounts_update'),
    path('account/delete/<int:pk>/', AccountDeleteView.as_view(), name='accounts_delete'),
        
    # Language Urls
    path('languages/', LanguageListView.as_view(), name='languages'),
    path('languages/create/', LanguageCreateView.as_view(), name='create_language'),
    path('languages/update/<int:pk>/', LanguageUpdateView.as_view(), name='update_language'),
    path('languages/delete/<int:pk>/', LanguageDeleteView.as_view(), name='delete_language'),
    
]

post/urls.py
from django.urls import path
from .views import PostList, PostDetail, CommentDelete

app_name = 'post'

urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('comment/delete/<int:pk>', CommentDelete.as_view(), name='delete_comment'),
    path('<slug:slug>/', PostDetail.as_view(), name='post'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import  i18n_patterns
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(
   openapi.Info(
      title="Blog API",
      default_version='v1',
      description="API for this blog",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('api/', include('account.api.urls')),
    path('api/', include('post.api.urls', namespace='post_api')),

    path('api/docs/', include_docs_urls(title='Blog APi')),
    path('api/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('post.urls', namespace='post')),
    # prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

post/models.py
import os
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.template.defaultfilters import slugify
from django.utils.translation import get_language
from PIL import Image
from unidecode import unidecode

def upload_image(instance, image_name):
    """ Make a path to the post image and change the name of the image to a post id

    Returns:
        [str]: [image path]
    """
    _ , extension = os.path.splitext(image_name)

    # return f"post_images/{instance.id}.{extension}"   
    return f"post_images/{instance.title}.{extension}"   

active_field_choices = [
    (True, _('Active')),
    (False, _('Inactive'))
]

class Language(models.Model):
    name = models.CharField(_('name'), max_length=25, null=True, blank=True)
    code = models.CharField(_('code'), max_length=5, null=True, blank=True)
    created_at = models.DateTimeField(_('created at'), auto_now=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now_add=True)
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)

    def __str__(self):
        return self.code
    
class Category(models.Model):
    name = models.CharField(_('name'), max_length=50)
    
    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        
    def __str__(self):
        return self.name
     
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('author'))
    title = models.CharField(_('title'), max_length=100)
    content = models.TextField(_('content'), max_length=4000)
    categories = models.ManyToManyField(Category, blank=True, verbose_name=_('categories'))
    image = models.ImageField(_('image'), upload_to=upload_image, blank=True, null=True)
    created_at = models.DateTimeField(_('created at'), auto_now=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now_add=True)
    published_at = models.DateTimeField(_('published at'), default=now)
    views_count = models.IntegerField(_('views count'), null=True, blank=True, default=0, editable=False)
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='posts', verbose_name=_('language'), null=True, blank=True)
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)
    slug = models.SlugField(null=True, blank=True, unique=True, max_length=100, allow_unicode=True)
    
    class Meta:
        ordering = ('-published_at', )
    
    @property
    def get_self_or_post_lang(self):
        # check are language existin Language model
        try:
            lang = Language.objects.get(code=get_language())
        except Language.DoesNotExist: # if not retrun default title
            return self
                    
        if self.language == lang:
            return self
        
        post_lang = self.post_lang.filter(language = lang)
        
        if post_lang:
            return post_lang.get()
        
        return self
        
    def get_title(self):
        return self.get_self_or_post_lang.title
    
    def get_content(self):
        return self.get_self_or_post_lang.content
    
    def get_categories(self):
        return self.get_self_or_post_lang.categories
    
    def get_language_code(self):
        return self.get_self_or_post_lang.language.code
            
        
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        """
            Overwrite save mehtod to make a slug to post, rename a image and resize a big image
        """

        # Make a post Slug
        if not self.pk:
            slug = slugify(unidecode(f"{self.title}"))

            slug_count = len(Post.objects.filter(slug=slug))
            if slug_count > 0:
                slug = f"{slug}-{slug_count}"

            self.slug = slug
            

        # Handle problem in upload_image function  (pk not generator yet)
        # if self.pk is None:
        #     post_image = self.image
        #     self.image = None
        #     super().save(*args, **kwargs)
        #     self.image = post_image

        super().save(*args, **kwargs)
        
        # image resize
        if self.image:
            try:
                img = Image.open(self.image.path)   
                if img.width > 800 or img.height > 800:
                    img.thumbnail( (800, 800) )
                    img.save(self.image.path)
            except:
                pass

class PostLanguage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_lang', verbose_name=_('post'))
    title = models.CharField(_('title'), max_length=100)
    content = models.TextField(_('content'), max_length=4000)
    categories = models.ManyToManyField(Category, blank=True, verbose_name=_('categories'))
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='posts_lan', verbose_name=_('language'))
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name=_('user'))
    content = models.TextField(_('content'), max_length=300)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, related_name='comments', verbose_name=_('post'),)
    created_at = models.DateTimeField(_('created at'), auto_now=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now_add=True)
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)
    
    def __str__(self):
        return self.content

post/forms.py
from django import  forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
        

account/api/views.py
from rest_framework.generics import CreateAPIView
from .serializers import CreateUserSerializer

class UserCreateAPIView(CreateAPIView):
    serializer_class = CreateUserSerializer

account/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.contrib import messages
from django.views.generic import FormView, View
from .forms import UserLoginForm,RegistrationForm, UserProfileForm


class RegisterView(FormView):
    model = User
    template_name = 'account/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('post:home')
    
    def get(self, *args, **kwargs):
        """ 
        check if user already login redierct to home page
        """
        if self.request.user.is_authenticated:
            return redirect('post:home')
        return super().get(*args, **kwargs)

    
    def form_valid(self, form):
        """ 
        override form_vaild finction to make user login after register
        Note:
            if you will add email verification delete this func   
            
        """
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)
    

class LoginPage(LoginView):
    template_name = 'account/login.html'
    form_class = UserLoginForm
    
    def get(self, request, *args, **kwargs):
        """ 
        check if user already login redierct to home page
        if user redierict from some place in site render login page in massage
        """
        if request.user.is_authenticated:
            if '?next=/' in request.get_full_path():
                return super().get(request, *args, **kwargs)
            else:
                return redirect('post:home')
        
        return super().get(request, *args, **kwargs)
    
class LogoutPage(LogoutView):
    next_page = reverse_lazy('post:home')

    # def get_next_page(self):
    #     messages.success(self.request, 'You have successfully logged out')
    #     super().get_next_page()
    
# Profile

class ProfileView(LoginRequiredMixin, View):
    template_name = 'account/profile.html'
    
    def get(self, request, *args, **kwargs):
        form = UserProfileForm(instance=self.request.user)
        return render(request, self.template_name, {'form':form})
    
    def post(self, request, *args, **kwargs):
        form = UserProfileForm(request.POST ,instance=self.request.user)
        if form.is_valid():
            form.save()
        form = UserProfileForm(instance=self.request.user)
        return self.get(request, *args, **kwargs)
    
    
 
    

post/api/views.py
from django.utils.timezone import now
from django.db.models import Q
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
    CreateAPIView,
    ListAPIView
    )
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from post.models import Post, Comment
from .serializers import (
    PostSerializer,
    PostDetailSerializer,
    PostCommentSerailzer,
    CommentSerailzer
    )
from .permissions import IsAuthorOrReadOnly, IsOwnerOrReadOnly

class PostAPIView(ListCreateAPIView):
    queryset = Post.objects.filter( Q(active=True) & Q(published_at__lte=now()) )
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class PostDetailAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.filter( Q(active=True) & Q(published_at__lte=now()) )
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]
    lookup_field = 'slug'


class CommentCreateApiView(CreateAPIView):
    model = Comment
    serializer_class = PostCommentSerailzer
    permission_classes = [IsAuthenticated,]


    def perform_create(self, serializer):
        slug = self.kwargs['slug']
        post = Post.objects.get(slug=slug)

        serializer.save(user=self.request.user, post=post)


class CommentListAPIView(ListAPIView):
    queryset = Comment.objects.filter(active=True)
    serializer_class = CommentSerailzer
    

class CommentDetialAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.filter(active=True)
    serializer_class = CommentSerailzer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

dashboard/templates/dashboard/base.html
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Dashboard</title>
	  <!-- Font Awesome -->
    <link rel="stylesheet" href="css/all.min.css">
	<!-- Main Template Css File -->
	<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
	{% if LANGUAGE_BIDI %}
		<!-- rtl Template Css File -->
		<link rel="stylesheet" href="{% static 'css/rtl.css' %}">
	{% endif %}	
	<!-- Google Fonts -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link 
	href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
</head>
<body>
	<nav>
		<div class="logo">
			<h1>{% trans 'dashboard' %}</h1>
		</div>
		{% if user.profile.is_admin_or_editor %}
		<ul>
			<li class="active">
				<a href="">
					<i class="fas fa-pen"></i>
					<p>{% trans 'dashboard' %}</p>
				</a>
			</li>
			<li>
				<a href="{% url 'dashboard:post_create' %}">
					<i class="fas fa-plus"></i>
					<p>{% trans 'add new post' %}</p>
				</a>
			</li>
			<li>
				<a href="{% url 'dashboard:posts' %}">
					<i class="fas fa-list"></i>
					<p>{% trans 'posts' %}</p>
				</a>
			</li>
			<li>
				<a href="{% url 'dashboard:posts_language' %}">
					<i class="fas fa-list"></i>
					<p>{% trans 'translated posts' %}</p>
				</a>
			</li>			
			<li>
				<a href="{% url 'dashboard:categories' %}">
					<i class="fas fa-list"></i>
					<p>{% trans 'categories' %}</p>
				</a>
			</li>
			<li>
				<a href="{% url 'dashboard:languages' %}">
					<i class="fas fa-list"></i>
					<p>{% trans 'languages' %}</p>
				</a>
			</li>									
			<li>
				<a href="{% url 'dashboard:comments' %}">
				<i class="fas fa-comments"></i>
					<p>{% trans 'comments' %}</p>
				</a>
			</li>
			<li>
				<a href="{% url 'profile' %}">
					<i class="fas fa-id-card-alt"></i>
					<p>{% trans 'profile' %}</p>
				</a>
			</li>
			{% if user.profile.is_admin %}
				<li>
					<a href="{% url 'dashboard:accounts' %}">
						<i class="fas fa-users"></i>
						<p>{% trans 'users' %}</p>
					</a>
				</li>
			{% endif %}
		</ul>
		{% endif %}
	</nav>
	<div class="main-content">
		<header>
			<form action="" method="get" class="search">
				<input type="search" name="search" id="" placeholder="{% trans 'search for something' %}..">
			</form>
			<div class="notification">
				<i class="far fa-bell"></i>
			</div>
			<div class="profile">
				<div class="image">
					<img src="https://e7.pngegg.com/pngimages/442/477/png-clipart-computer-icons-user-profile-avatar-profile-heroes-profile.png" alt="profile-image">
				</div>
				<p>{% trans 'admin' %}</p>
			</div>
		</header>
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<section class="content">
            {% block content %}
            {% endblock content %}
		</section>
	</div>
</body>
</html>

dashboard/templates/dashboard/category_list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% block content %}
<div class="content-header">
  <legend>Categories List</legend>
  <form action="{% url 'dashboard:create_category' %}" method="post">
      {% csrf_token %}
      <input type="text" name="name" maxlength="50" required="" id="id_name" class='special' placeholder="{% trans 'write category name here' %}">
      <input type="submit" value="{% trans 'add category' %}" class="btn info">
  </form>
</div>
<div class="table">
  <table>
  <thead>
    <tr>
      <th>{% trans 'name' %}</th>
      <th>{% trans 'category number' %}</th>
      <th>{% trans 'update' %}</th>
      <th>{% trans 'delete' %}</th>
      <th>{% trans 'see category' %}</th>
    </tr>
  </thead>
  <tbody>
    {% for category in categories %}
      <tr>
        <td>{{category.name}}</td>
        <td>{{category.post_set.all.count}}</td>
        <td><a href="{% url 'dashboard:update_category' category.id %}" class="btn btn-sm warning">{% trans 'Update' %}</a></td>
        <td><a href="{% url 'dashboard:delete_category' category.id %}" class="btn btn-sm danger">{% trans 'Delete' %}</a></td>
        <td><a class="btn btn-sm info" href="{% url 'post:home' %}?category={{category}}">{% trans 'see category' %}</a></td>
      </tr>
    {% endfor %}      
  </tbody>
  </table>				
</div>
{% endblock content  %}

dashboard/templates/dashboard/confirm_delete.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% block content %}
<div class="content-header">
  <legend>
    {% trans 'delete' %} {{object}}
  </legend>
</div>
<p>{% trans 'Are You Sure You Want Delete' %}'{{object}}'</p>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete it" class="btn info">
  <a href="
  {% if 'comment' in request.path %}
    {% url 'dashboard:comments' %}  
  {% elif 'post' in request.path %}    
    {% url 'dashboard:posts' %}
  {% elif 'category' in request.path %}
    {% url 'dashboard:categories' %}
  {% else %}
    {% url 'dashboard:accounts' %}
  {% endif %}
  " class="btn info">{% trans 'no' %}</a>
</form>
{% endblock content  %}

dashboard/templates/dashboard/language_list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% block content %}
<div class="content-header">
  <legend>Language List</legend>
    <a href="{% url 'dashboard:create_language' %}"  class="btn info" >create language</a>
</div>
<div class="table">
  <table>
  <thead>
    <tr>
      <th>{% trans 'name' %}</th>
      <th>{% trans 'code' %}</th>
      <th>{% trans 'update' %}</th>
      <th>{% trans 'delete' %}</th>
    </tr>
  </thead>
  <tbody>
    {% for language in languages %}
      <tr>
        <td>{{language.name}}</td>
        <td>{{language.code}}</td>
        <td><a href="{% url 'dashboard:update_language' language.id %}" class="btn btn-sm warning">{% trans 'Update' %}</a></td>
        <td><a href="{% url 'dashboard:delete_language' language.id %}" class="btn btn-sm danger">{% trans 'Delete' %}</a></td>
      </tr>
    {% endfor %}      
  </tbody>
  </table>				
</div>
{% endblock content  %}

dashboard/templates/dashboard/post_form.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% trans 'new post' %}</title>
	<link rel="stylesheet" href="{% static 'dashboard/css/new_post.css' %}">
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
	</head>
<body>
	<header>
		<h2>{% trans 'create new post' %}</h2>
		<ul>
			<li><a href="{% url 'post:home' %}">{% trans 'Home' %}</a></li>
			<li><a href="{% url 'dashboard:posts' %}">{% trans 'Dashboard' %}</a></li>
		</ul>
	</header>
	<div class="new-form">
		<form action="" method="post" class="post-form" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-header">
				<div class="btns">
				</div>
			</div>
			<div class="body">
				{% if form.errors %}
					{{form.errors}}
				{% endif %}
				<div class="col">
					<label for="id_categories">{{form.post.label}}</label>
					{{form.post}}
					<label for="id_active">{{form.language.label}}</label>			
					{{form.language}}					
					<label for="id_categories">{{form.categories.label}}</label>
					{{form.categories}}
					<a href="{% url 'dashboard:create_category' %}">{% trans 'add new category' %}</a>
					<label for="id_published_at">{{form.published_at.label}}</label>		
					{{form.published_at}}
					{% if 'create' in request.path %}			
						<label for="id_image">{{form.image.label}}</label>					
						{{form.image}}
					{% endif %}						
					<label for="id_active">{{form.active.label}}</label>					
					{{form.active}}
					<input type="submit" value="{% trans 'save' %}">
				</div>
				<div class="content">
					{{form.title}}
					{{form.content}}
				</div>
			</div>
		</form>
	</div>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
					integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
	<script>
		$(document).ready(function() {
				$('#id_categories').select2();
		});		
	</script>
</body>
</html>

dashboard/templates/dashboard/post_list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% block content %}
	<div class="content-header">
		<legend>{% trans 'posts list' %}</legend>
		<a href="{% url 'dashboard:post_create' %}" class="btn info">{% trans 'add post' %}</a>
	</div>
	<div class="table">
		<table>
		<thead>
			<tr>
				<th>{% trans 'title' %}</th>
				<th>{% trans 'editor' %}</th>
				<th>{% trans 'categories' %}</th>
				<th>{% trans 'languages' %}</th>
				<th>{% trans 'views' %}</th>
				<th>{% trans 'published at' %}</th>
				<th>{% trans 'add translate' %}</th>
				<th>{% trans 'stat' %}</th>
				<th>{% trans 'delete' %}</th>
				<th>{% trans 'update' %}</th>
			</tr>
		</thead>
		<tbody>
			{% for post in posts %}
			<tr>
				<td>
					<a href="{% url 'post:post' post.slug %}">
						{{post.get_title|slice:'6'}}
						{% if post.get_title|length > 6 %}
						...
						{% endif %}
					</a>
				</td>
				<td>{{post.author}}</td>
				<td>
					{% for category in post.get_categories.all %}
						<a href="{% url 'post:home'%}?category={{category}}">{{category|slice:'6'}}</a>
						{% if not forloop.last %}
						,
						{% endif %}
						{% empty %}
							{% trans 'no category' %}
					{% endfor %}
				</td>		
				<td>
					<a href="{% url 'post:post' post.slug %}">{{post.language}}</a>
					{% for post_lan in post.post_lang.all %}
						, <a href="/{{post_lan.language}}/{{post.slug}}">{{post_lan.language}}</a>
					{% endfor %}
				</td>						
				<td>{{post.views_count}}</td>
				<td>{{post.published_at|date:'d M Y'}}</td>
				<td><a href="{% url 'dashboard:post_language_create' post.id %}" class="btn btn-sm info">{% trans 'Add Translate' %}</a></td>
				{% if post.active %}
				<td><div class="btn btn-sm info">{% trans 'Active' %}</div></td>
				{% else %}
				<td><div class="btn btn-sm warning">{% trans 'Inactive' %}</div></td>
				{% endif %}
				<td><a href="{% url 'dashboard:post_update' post.slug %}"><div class="btn btn-sm warning">{% trans 'update' %}</div></a></td>
				<td><a href="{% url 'dashboard:post_delete' post.slug %}"><div class="btn btn-sm danger">{% trans 'delete' %}</div></a></td>
			</tr>
			{% empty %}
				<p>{% trans 'no posts' %}</p>
			{% endfor %}
		</tbody>
		</table>				
	</div>
{% endblock content  %}